mariadb:
  dp_name: app-db
  image: mariadb:latest
  password: MXFhekBXU1g= 
  port: 3306

wordpress:
  dp_name: app-web
  port: 80
  image: wordpress:latest

svc_db:
  name: app-svc-db

svc_web:
  name: app-svc-web
  port: 80

ingress:
  name: myingress
  hostname: homework.loc
  
secret:
  name: mysecret