---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.password }}
  WORDPRESS_DB_PASSWORD: {{ .Values.mariadb.password }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc_db.name }}
spec:
  selector:
    app: maria-db
  ports:
  - port: {{ .Values.mariadb.port }}
    targetPort: {{ .Values.mariadb.port }}
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc_web.name }}
spec:
  selector:
    app: wordpress-web
  ports:
  - port: {{ .Values.svc_web.port}}
    targetPort: {{ .Values.wordpress.port }}
    protocol: TCP
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mariadb.dp_name }}
spec:
  selector:
    matchLabels:
      app: maria-db
  template:
    metadata:
      labels:
        app: maria-db
    spec:
      containers:
      - name: mariadb
        image: {{ .Values.mariadb.image }}
        env:
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: maria-vol
          mountPath: /var/lib/mysql
      volumes:
      - name: maria-vol
        emptyDir: {}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wordpress.dp_name }}
spec:
  selector:
    matchLabels:
      app: wordpress-web
  template:
    metadata:
      labels:
        app: wordpress-web
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image }}
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Values.svc_db.name }}
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: WORDPRESS_DB_PASSWORD
        volumeMounts:
        - name: wordpress-vol
          mountPath: /var/www/html
      volumes:
      - name: wordpress-vol
        emptyDir: {}
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths: 
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.svc_web.name }}
            port:
              number: {{ .Values.svc_web.port}}